import { createTranslator, en, type Dictionary, type Translate } from './i18n';

// Language packs for the panel chrome and the engine's plain-language messages. Activity names come
// from the room's design, so designers name those in whichever language they like. A key missing
// from a pack falls back to English.
const es: Dictionary = {
  ready: 'Todo listo.',
  starting: 'Preparando la sala…',
  stopping: 'Apagando la sala…',
  room_off: 'La sala está apagada. Elija qué desea hacer.',
  presenting: 'Mostrando {source}.',
  plug_in_source: 'Conecte su cable para {source}.',
  recording: 'Grabando. Los micrófonos están activos.',
  recording_saved: 'Grabación guardada.',
  fault_device: '{device} no responde. Inténtelo de nuevo o contacte con soporte.',
  fault_generic: 'Algo salió mal. Inténtelo de nuevo o contacte con soporte.',
  switch_source: 'Se acaba de conectar {source}. ¿Cambiar a él?',
  auto_off: 'Parece que nadie usa esta sala. Se apagará en breve.',
  'nav.label': 'Actividades',
  'sources.title': 'Mostrar desde',
  'source.connected': 'Cable conectado',
  'source.disconnected': 'Sin cable',
  'record.start': 'Iniciar grabación',
  'record.stop': 'Detener grabación',
  'prompt.accept': 'Cambiar',
  'prompt.decline': 'Mantener actual',
  'prompt.seconds': 'Cambiando en {seconds} s',
  'warning.stay': 'Mantener encendida',
  'warning.seconds': 'Apagando en {seconds} s',
  'volume.label': 'Volumen',
  'volume.up': 'Subir volumen',
  'volume.down': 'Bajar volumen',
  'volume.mute': 'Silenciar',
  'volume.unmute': 'Activar sonido',
  'start.title': '¿Qué desea hacer?',
  'activity.running': 'En marcha',
  'session.connecting': 'Conectando con la sala…',
  'session.reconnecting': 'Reconectando con la sala…',
  'session.error': 'Este panel no puede conectar con la sala en este momento.',
  'phone.button': 'Controlar desde su teléfono',
  'phone.title': 'Escanee con la cámara de su teléfono para controlar esta sala.',
  'phone.close': 'Cerrar',
  'pin.title': 'Introduzca el PIN',
  'pin.submit': 'Desbloquear',
  'pin.clear': 'Borrar',
  'idle.begin': 'Toque para comenzar',
  'idle.support': '¿Necesita ayuda?',
  'volume.muted': 'Silenciado',
  'fn.cameras': 'Cámaras',
  'fn.microphones': 'Micrófonos',
  'fn.controls': 'Controles de la sala',
  'fn.presets': 'Vistas de cámara',
  'fn.move': 'Mover la cámara',
  'cam.up': 'Arriba',
  'cam.down': 'Abajo',
  'cam.left': 'Izquierda',
  'cam.right': 'Derecha',
  'cam.zoom_in': 'Acercar',
  'cam.zoom_out': 'Alejar',
  'mic.muted': 'Silenciado',
  'mic.live': 'Activo',
  'controls.lights': 'Iluminación',
  'controls.blinds': 'Persianas y pantallas',
  'mover.open': 'Abrir',
  'mover.close': 'Cerrar',
  'mover.up': 'Subir',
  'mover.down': 'Bajar',
  'quick.more': 'Acciones rápidas',
  'linking.button': 'Unir salas',
  'linking.title': 'Unir salas',
  'linking.space': 'Unidas: {rooms}',
  'linking.alone': 'Esta sala funciona sola.',
  'linking.none': 'No hay salas con las que unir aquí.',
  'linking.option.combine': 'Unir con {rooms}',
  'linking.option.link': 'Unir {rooms}',
  'linking.linked': 'Unida con {rooms}',
  'linking.combine': 'Unir',
  'linking.separate': 'Separar',
  'linking.unavailable': 'Aún no configurada',
  'linking.confirm.combine': '¿Unir con {rooms}?',
  'linking.confirm.combine.body': 'Sus pantallas, sonido y controles funcionarán juntos como uno.',
  'linking.confirm.separate': '¿Separar de {rooms}?',
  'linking.confirm.separate.body': 'Cada sala volverá a funcionar por separado.',
  'quick.display.blank': 'Pantalla en negro',
  'quick.mics.privacy_mute': 'Silencio de privacidad',
  'sheet.close': 'Cerrar',
  'power.button': 'Apagar',
  'power.title': '¿Apagar el sistema?',
  'power.body': 'Las pantallas y el audio se apagarán.',
  'power.confirm': 'Apagar',
  'power.cancel': 'Cancelar',
};

const fr: Dictionary = {
  ready: 'Prêt.',
  starting: 'Préparation de la salle…',
  stopping: 'Extinction de la salle…',
  room_off: 'La salle est éteinte. Choisissez ce que vous souhaitez faire.',
  presenting: 'Affichage de {source}.',
  plug_in_source: 'Branchez votre câble pour {source}.',
  recording: 'Enregistrement en cours. Les microphones sont actifs.',
  recording_saved: 'Enregistrement sauvegardé.',
  fault_device: '{device} ne répond pas. Réessayez ou contactez l’assistance.',
  fault_generic: 'Un problème est survenu. Réessayez ou contactez l’assistance.',
  switch_source: '{source} vient d’être branché. Basculer dessus ?',
  auto_off: 'Personne ne semble utiliser cette salle. Extinction imminente.',
  'nav.label': 'Activités',
  'sources.title': 'Afficher depuis',
  'source.connected': 'Câble connecté',
  'source.disconnected': 'Pas de câble',
  'record.start': 'Démarrer l’enregistrement',
  'record.stop': 'Arrêter l’enregistrement',
  'prompt.accept': 'Basculer',
  'prompt.decline': 'Garder l’actuelle',
  'prompt.seconds': 'Bascule dans {seconds} s',
  'warning.stay': 'Rester allumée',
  'warning.seconds': 'Extinction dans {seconds} s',
  'volume.label': 'Volume',
  'volume.up': 'Augmenter le volume',
  'volume.down': 'Baisser le volume',
  'volume.mute': 'Couper le son',
  'volume.unmute': 'Rétablir le son',
  'start.title': 'Que souhaitez-vous faire ?',
  'activity.running': 'En cours',
  'session.connecting': 'Connexion à la salle…',
  'session.reconnecting': 'Reconnexion à la salle…',
  'session.error': 'Ce panneau ne peut pas joindre la salle pour le moment.',
  'phone.button': 'Commander depuis votre téléphone',
  'phone.title': 'Scannez avec l’appareil photo de votre téléphone pour commander cette salle.',
  'phone.close': 'Fermer',
  'pin.title': 'Saisissez le code PIN',
  'pin.submit': 'Déverrouiller',
  'pin.clear': 'Effacer',
  'idle.begin': 'Touchez pour commencer',
  'idle.support': 'Besoin d’aide ?',
  'volume.muted': 'Son coupé',
  'fn.cameras': 'Caméras',
  'fn.microphones': 'Microphones',
  'fn.controls': 'Commandes de la salle',
  'fn.presets': 'Vues de caméra',
  'fn.move': 'Déplacer la caméra',
  'cam.up': 'Haut',
  'cam.down': 'Bas',
  'cam.left': 'Gauche',
  'cam.right': 'Droite',
  'cam.zoom_in': 'Zoom avant',
  'cam.zoom_out': 'Zoom arrière',
  'mic.muted': 'Coupé',
  'mic.live': 'Actif',
  'controls.lights': 'Éclairage',
  'controls.blinds': 'Stores et écrans',
  'mover.open': 'Ouvrir',
  'mover.close': 'Fermer',
  'mover.up': 'Monter',
  'mover.down': 'Descendre',
  'quick.more': 'Actions rapides',
  'linking.button': 'Relier les salles',
  'linking.title': 'Relier les salles',
  'linking.space': 'Reliées : {rooms}',
  'linking.alone': 'Cette salle fonctionne seule.',
  'linking.none': 'Aucune salle à relier ici.',
  'linking.option.combine': 'Relier avec {rooms}',
  'linking.option.link': 'Relier {rooms}',
  'linking.linked': 'Reliée avec {rooms}',
  'linking.combine': 'Relier',
  'linking.separate': 'Séparer',
  'linking.unavailable': 'Pas encore configurée',
  'linking.confirm.combine': 'Relier avec {rooms} ?',
  'linking.confirm.combine.body':
    'Leurs écrans, le son et les commandes fonctionneront ensemble comme un seul.',
  'linking.confirm.separate': 'Séparer de {rooms} ?',
  'linking.confirm.separate.body': 'Chaque salle fonctionnera de nouveau seule.',
  'quick.display.blank': 'Écran noir',
  'quick.mics.privacy_mute': 'Silence confidentiel',
  'sheet.close': 'Fermer',
  'power.button': 'Éteindre',
  'power.title': 'Éteindre le système ?',
  'power.body': 'Les écrans et le son seront éteints.',
  'power.confirm': 'Éteindre',
  'power.cancel': 'Annuler',
};

const de: Dictionary = {
  ready: 'Bereit.',
  starting: 'Der Raum wird vorbereitet…',
  stopping: 'Der Raum wird ausgeschaltet…',
  room_off: 'Der Raum ist aus. Wählen Sie, was Sie tun möchten.',
  presenting: '{source} wird angezeigt.',
  plug_in_source: 'Schließen Sie Ihr Kabel für {source} an.',
  recording: 'Aufnahme läuft. Die Mikrofone sind aktiv.',
  recording_saved: 'Aufnahme gespeichert.',
  fault_device:
    '{device} antwortet nicht. Versuchen Sie es erneut oder wenden Sie sich an den Support.',
  fault_generic:
    'Etwas ist schiefgelaufen. Versuchen Sie es erneut oder wenden Sie sich an den Support.',
  switch_source: '{source} wurde gerade angeschlossen. Dorthin wechseln?',
  auto_off: 'Anscheinend nutzt niemand diesen Raum. Er wird gleich ausgeschaltet.',
  'nav.label': 'Aktivitäten',
  'sources.title': 'Anzeigen von',
  'source.connected': 'Kabel verbunden',
  'source.disconnected': 'Kein Kabel',
  'record.start': 'Aufnahme starten',
  'record.stop': 'Aufnahme beenden',
  'prompt.accept': 'Wechseln',
  'prompt.decline': 'Aktuelle behalten',
  'prompt.seconds': 'Wechsel in {seconds} s',
  'warning.stay': 'Anlassen',
  'warning.seconds': 'Ausschalten in {seconds} s',
  'volume.label': 'Lautstärke',
  'volume.up': 'Lauter',
  'volume.down': 'Leiser',
  'volume.mute': 'Stummschalten',
  'volume.unmute': 'Ton einschalten',
  'start.title': 'Was möchten Sie tun?',
  'activity.running': 'Läuft',
  'session.connecting': 'Verbindung zum Raum wird hergestellt…',
  'session.reconnecting': 'Verbindung zum Raum wird wiederhergestellt…',
  'session.error': 'Dieses Bedienfeld erreicht den Raum gerade nicht.',
  'phone.button': 'Mit dem Smartphone steuern',
  'phone.title': 'Mit der Smartphone-Kamera scannen, um diesen Raum zu steuern.',
  'phone.close': 'Schließen',
  'pin.title': 'PIN eingeben',
  'pin.submit': 'Entsperren',
  'pin.clear': 'Löschen',
  'idle.begin': 'Zum Starten berühren',
  'idle.support': 'Brauchen Sie Hilfe?',
  'volume.muted': 'Stumm',
  'fn.cameras': 'Kameras',
  'fn.microphones': 'Mikrofone',
  'fn.controls': 'Raumsteuerung',
  'fn.presets': 'Kameraansichten',
  'fn.move': 'Kamera bewegen',
  'cam.up': 'Hoch',
  'cam.down': 'Runter',
  'cam.left': 'Links',
  'cam.right': 'Rechts',
  'cam.zoom_in': 'Heranzoomen',
  'cam.zoom_out': 'Herauszoomen',
  'mic.muted': 'Stumm',
  'mic.live': 'Aktiv',
  'controls.lights': 'Beleuchtung',
  'controls.blinds': 'Jalousien und Leinwände',
  'mover.open': 'Öffnen',
  'mover.close': 'Schließen',
  'mover.up': 'Anheben',
  'mover.down': 'Absenken',
  'quick.more': 'Schnellaktionen',
  'linking.button': 'Räume verbinden',
  'linking.title': 'Räume verbinden',
  'linking.space': 'Verbunden: {rooms}',
  'linking.alone': 'Dieser Raum arbeitet allein.',
  'linking.none': 'Hier gibt es keine Räume zum Verbinden.',
  'linking.option.combine': 'Mit {rooms} verbinden',
  'linking.option.link': '{rooms} verbinden',
  'linking.linked': 'Verbunden mit {rooms}',
  'linking.combine': 'Verbinden',
  'linking.separate': 'Trennen',
  'linking.unavailable': 'Noch nicht eingerichtet',
  'linking.confirm.combine': 'Mit {rooms} verbinden?',
  'linking.confirm.combine.body':
    'Bildschirme, Ton und Steuerung arbeiten dann zusammen als eine Einheit.',
  'linking.confirm.separate': 'Von {rooms} trennen?',
  'linking.confirm.separate.body': 'Jeder Raum arbeitet dann wieder allein.',
  'quick.display.blank': 'Bildschirm ausblenden',
  'quick.mics.privacy_mute': 'Datenschutz-Stummschaltung',
  'sheet.close': 'Schließen',
  'power.button': 'Ausschalten',
  'power.title': 'System ausschalten?',
  'power.body': 'Bildschirme und Audio werden ausgeschaltet.',
  'power.confirm': 'Ausschalten',
  'power.cancel': 'Abbrechen',
};

export const LANGUAGES: Record<string, { label: string; dictionary: Dictionary }> = {
  en: { label: 'English', dictionary: {} },
  es: { label: 'Español', dictionary: es },
  fr: { label: 'Français', dictionary: fr },
  de: { label: 'Deutsch', dictionary: de },
};

/** A translator for a language code such as "es" or "fr-CA". Unknown languages get English. */
export function translatorFor(language?: string | null): Translate {
  const code = (language ?? 'en').toLowerCase().split(/[-_]/)[0]!;
  return createTranslator(LANGUAGES[code]?.dictionary ?? {});
}

export const languageOptions = () =>
  Object.entries(LANGUAGES).map(([code, l]) => ({ code, label: l.label }));

export const ENGLISH_KEYS = Object.keys(en);
